In [2]:
import numpy as np

# 3D array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]],
                   [[13, 14, 15], [16, 17, 18]]])

# Selecting all elements along the first axis, and only the first element along the last axis
selected_3d = arr_3d[..., 0:1]

print(selected_3d)

[[[ 1]
  [ 4]]

 [[ 7]
  [10]]

 [[13]
  [16]]]


In [3]:
print(arr_3d[0:1])

[[[1 2 3]
  [4 5 6]]]


In [4]:
import torch

iou_b1 = torch.tensor([[21,10],[1,2]])
iou_b2 = torch.tensor([[18,9],[5,6]])
print(iou_b1)

ious = torch.cat([iou_b1.unsqueeze(0), iou_b2.unsqueeze(0)], dim=2)
print(ious)

# Take the box with highest IoU out of the two prediction
# Note that bestbox will be indices of 0, 1 for which bbox was best
iou_maxes, bestbox = torch.max(ious, dim=0)
print(iou_maxes)
print(bestbox)

tensor([[21, 10],
        [ 1,  2]])
tensor([[[21, 10, 18,  9],
         [ 1,  2,  5,  6]]])
tensor([[21, 10, 18,  9],
        [ 1,  2,  5,  6]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])


In [5]:
import pandas as pd
import os
from PIL import Image

annotations = pd.read_csv("/Users/yohanabeysinghe/Mac/0. ML/Datasets/PascalVOC YOLO/test.csv", header=None)
img_dir = "/Users/yohanabeysinghe/Mac/0. ML/Datasets/PascalVOC YOLO/images"
label_dir = "/Users/yohanabeysinghe/Mac/0. ML/Datasets/PascalVOC YOLO/labels"
S= 7
B= 2
C= 20 

In [6]:
index = 0
label_path = os.path.join(label_dir, annotations.iloc[index, 1])
label_path


'/Users/yohanabeysinghe/Mac/0. ML/Datasets/PascalVOC YOLO/labels/000001.txt'

In [7]:
boxes = []

with open(label_path) as f:
    for label in f.readlines():
        class_label, x, y, width, height = [
            float(x) if float(x) != int(float(x)) else int(x)
            for x in label.replace("\n", "").split()
        ]

        boxes.append([class_label, x, y, width, height])

In [8]:
boxes

[[11, 0.34419263456090654, 0.611, 0.4164305949008499, 0.262],
 [14, 0.509915014164306, 0.51, 0.9745042492917847, 0.972]]

In [9]:
img_path = os.path.join(img_dir, annotations.iloc[index, 0])
image = Image.open(img_path)

In [10]:
import torch
boxes = torch.tensor(boxes)
boxes

tensor([[11.0000,  0.3442,  0.6110,  0.4164,  0.2620],
        [14.0000,  0.5099,  0.5100,  0.9745,  0.9720]])

In [11]:
label_matrix = torch.zeros((S, S, C + 5 * B))
for box in boxes:
    class_label, x, y, width, height = box.tolist()
    print(x,y)
    class_label = int(class_label)
    print(class_label)
    i, j = int(S * y), int(S * x)
    print(i,j)

0.34419262409210205 0.6110000014305115
11
4 2
0.5099149942398071 0.5099999904632568
14
3 3


In [12]:
x_cell, y_cell = S * x - j, S * y - i

print(x_cell, y_cell)

0.5694049596786499 0.5699999332427979


In [13]:
width_cell, height_cell = (width * S, height * S,)

print(width_cell, height_cell)

6.8215296268463135 6.804000020027161


In [15]:
label_matrix.shape

torch.Size([7, 7, 30])

In [16]:
if label_matrix[i, j, 20] == 0:
    # Set that there exists an object
    label_matrix[i, j, 20] = 1

    # Box coordinates
    box_coordinates = torch.tensor(
        [x_cell, y_cell, width_cell, height_cell]
    )

    label_matrix[i, j, 21:25] = box_coordinates

    # Set one hot encoding for class_label
    label_matrix[i, j, class_label] = 1

In [18]:
label_matrix[i,j]

tensor([0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 1.0000, 0.0000, 0.0000, 0.0000,
        0.0000, 0.0000, 1.0000, 0.5694, 0.5700, 6.8215, 6.8040, 0.0000, 0.0000,
        0.0000, 0.0000, 0.0000])