In [13]:
import numpy as np

# 3D array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]],
                   [[13, 14, 15], [16, 17, 18]]])

# Selecting all elements along the first axis, and only the first element along the last axis
selected_3d = arr_3d[..., 0:1]

print(selected_3d)

[[[ 1]
  [ 4]]

 [[ 7]
  [10]]

 [[13]
  [16]]]


In [14]:
print(arr_3d[0:1])

[[[1 2 3]
  [4 5 6]]]


In [10]:
import torch

iou_b1 = torch.tensor([[21,10],[1,2]])
iou_b2 = torch.tensor([[18,9],[5,6]])
print(iou_b1)

ious = torch.cat([iou_b1.unsqueeze(0), iou_b2.unsqueeze(0)], dim=2)
print(ious)

# Take the box with highest IoU out of the two prediction
# Note that bestbox will be indices of 0, 1 for which bbox was best
iou_maxes, bestbox = torch.max(ious, dim=0)
print(iou_maxes)
print(bestbox)

tensor([[21, 10],
        [ 1,  2]])
tensor([[[21, 10, 18,  9],
         [ 1,  2,  5,  6]]])
tensor([[21, 10, 18,  9],
        [ 1,  2,  5,  6]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
