In [13]:
import numpy as np

# 3D array
arr_3d = np.array([[[1, 2, 3], [4, 5, 6]],
                   [[7, 8, 9], [10, 11, 12]],
                   [[13, 14, 15], [16, 17, 18]]])

# Selecting all elements along the first axis, and only the first element along the last axis
selected_3d = arr_3d[..., 0:1]

print(selected_3d)

[[[ 1]
  [ 4]]

 [[ 7]
  [10]]

 [[13]
  [16]]]


In [14]:
print(arr_3d[0:1])

[[[1 2 3]
  [4 5 6]]]
